/*
 *    Copyright (C) 2012 Hai Bison
 *
 *    See the file LICENSE at the root directory of this project for copying
 *    permission.
 */

package group.pals.desktop.app.apksigner;

import group.pals.desktop.app.apksigner.i18n.Messages;

import javax.swing.JPanel;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import java.awt.GridBagConstraints;
import javax.swing.JPasswordField;
import java.awt.Insets;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.Font;
import javax.swing.border.TitledBorder;

/**
 * Panel for keystore utilities.
 * 
 * @author Hai Bison
 * @since v1.6 beta
 */
public class PanelKeyTools extends JPanel {

    /**
     * Auto-generated by Eclipse.
     */
    private static final long serialVersionUID = 416508787192252476L;

    /**
     * The class name.
     */
    private static final String CLASSNAME = PanelKeyTools.class.getName();

    /**
     * This key holds the last working directory.
     */
    private static final String PKEY_LAST_WORKING_DIR = CLASSNAME
            + ".last_working_dir";
    private JPasswordField passwordField;

    /**
     * Create the panel.
     */
    public PanelKeyTools() {
        GridBagLayout gridBagLayout = new GridBagLayout();
        gridBagLayout.columnWidths = new int[] { 0, 0 };
        gridBagLayout.rowHeights = new int[] { 0, 0, 0, 0, 0 };
        gridBagLayout.columnWeights = new double[] { 1.0, Double.MIN_VALUE };
        gridBagLayout.rowWeights = new double[] { 0.0, 0.0, 0.0, 1.0,
                Double.MIN_VALUE };
        setLayout(gridBagLayout);

        JButton btnNewButton = new JButton(
                Messages.getString("desc_load_key_file"));
        GridBagConstraints gbc_btnNewButton = new GridBagConstraints();
        gbc_btnNewButton.insets = new Insets(10, 3, 3, 3);
        gbc_btnNewButton.gridx = 0;
        gbc_btnNewButton.gridy = 0;
        add(btnNewButton, gbc_btnNewButton);

        passwordField = new JPasswordField();
        passwordField.setBorder(new TitledBorder(null, Messages
                .getString("password"), TitledBorder.LEADING, TitledBorder.TOP,
                null, null));
        GridBagConstraints gbc_passwordField = new GridBagConstraints();
        gbc_passwordField.insets = new Insets(3, 3, 3, 3);
        gbc_passwordField.fill = GridBagConstraints.HORIZONTAL;
        gbc_passwordField.gridx = 0;
        gbc_passwordField.gridy = 1;
        add(passwordField, gbc_passwordField);

        JButton btnNewButton_1 = new JButton(Messages.getString("list_entries"));
        GridBagConstraints gbc_btnNewButton_1 = new GridBagConstraints();
        gbc_btnNewButton_1.insets = new Insets(3, 3, 3, 3);
        gbc_btnNewButton_1.gridx = 0;
        gbc_btnNewButton_1.gridy = 2;
        add(btnNewButton_1, gbc_btnNewButton_1);

        JScrollPane scrollPane = new JScrollPane();
        GridBagConstraints gbc_scrollPane = new GridBagConstraints();
        gbc_scrollPane.insets = new Insets(3, 3, 3, 3);
        gbc_scrollPane.fill = GridBagConstraints.BOTH;
        gbc_scrollPane.gridx = 0;
        gbc_scrollPane.gridy = 3;
        add(scrollPane, gbc_scrollPane);

        JTextArea textArea = new JTextArea();
        textArea.setEditable(false);
        textArea.setFont(new Font("Monospaced", textArea.getFont().getStyle(),
                textArea.getFont().getSize()));
        textArea.setMargin(new Insets(9, 9, 9, 9));
        textArea.setTabSize(4);
        scrollPane.setViewportView(textArea);
    }// PanelKeyTools()

}
