/*
 *   Copyright 2012 Hai Bison
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

/*
 * MainFrame.java
 *
 * Created on Feb 15, 2012, 5:42:54 PM
 */
package group.pals.android.utils.apksigner;

import group.pals.android.utils.apksigner.panels.PanelKeygen;
import group.pals.android.utils.apksigner.panels.PanelSigner;
import group.pals.android.utils.apksigner.utils.Files;
import group.pals.android.utils.apksigner.utils.MsgBox;
import group.pals.android.utils.apksigner.utils.UI;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.AbstractAction;

/**
 *
 * @author Hai Bison
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();

        btnChooseJdkPath.setAction(ActionChooseJdkPath);
        miExit.setAction(ActionExit);
        miAbout.setAction(ActionAbout);

        tabbedPane.add("Key Generator", new PanelKeygen(this));
        tabbedPane.add("APK Signer", new PanelSigner(this));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtJdkPath = new javax.swing.JTextField();
        btnChooseJdkPath = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtJdkPath.setEditable(false);
        txtJdkPath.setBorder(javax.swing.BorderFactory.createTitledBorder("(For Windows users) JDK Path:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtJdkPath, gridBagConstraints);

        btnChooseJdkPath.setText("Choose...");
        jPanel1.add(btnChooseJdkPath, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(tabbedPane, gridBagConstraints);

        jMenu1.setText("File");

        miExit.setText("jMenuItem1");
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        miAbout.setText("jMenuItem1");
        jMenu2.add(miAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainFrame m = new MainFrame();

                UI.setWindowCenterScreen(m, 51);

                Package pkg = MainFrame.class.getPackage();
                m.setTitle(String.format("%s %s",
                        pkg != null ? pkg.getImplementationTitle() : "apk-ssigner",
                        pkg != null ? pkg.getImplementationVersion() : "[unknown]"));

                m.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseJdkPath;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtJdkPath;
    // End of variables declaration//GEN-END:variables
    private File jdkDir;

    /**
     * @return the keyFile
     */
    public File getJdkDir() {
        return jdkDir;
    }

    /**
     * @param v the keyFile to set
     */
    public void setJdkDir(File v) {
        this.jdkDir = v;
        txtJdkPath.setText(v != null ? v.getAbsolutePath() : null);

    }
    /*
     * ACTION LISTENERS
     */
    private final AbstractAction ActionChooseJdkPath = new AbstractAction("Choose...") {

        public void actionPerformed(ActionEvent e) {
            File file = Files.chooseDir(null);
            setJdkDir(file);
        }
    };//ActionChooseJdkPath
    private final AbstractAction ActionExit = new AbstractAction("Exit") {

        public void actionPerformed(ActionEvent e) {
            System.exit(0);
        }
    };//ActionExit
    private final AbstractAction ActionAbout = new AbstractAction("About...") {

        public void actionPerformed(ActionEvent e) {
            Package pkg = MainFrame.class.getPackage();
            String msg = String.format("%s %s\n\n"
                    + "...by Hai Bison\n\n"
                    + "License: Apache License 2.0\n"
                    + "Homepage: https://sites.google.com/site/haitimeid/\n"
                    + "Code page: http://code.google.com/p/apk-signer/\n",
                    pkg != null ? pkg.getImplementationTitle() : "apk-signer",
                    pkg != null ? pkg.getImplementationVersion() : "[unknown]");
            MsgBox.showHugeInfoMsg(null, null, msg, 400, 200);
        }
    };//ActionAbout
}
