/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Feb 15, 2012, 5:42:54 PM
 */
package group.pals.android.utils.apksigner;

import group.pals.android.utils.apksigner.panels.PanelKeygen;
import group.pals.android.utils.apksigner.panels.PanelSigner;
import group.pals.android.utils.apksigner.utils.Files;
import group.pals.android.utils.apksigner.utils.UI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 *
 * @author root
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();

        btnChooseJdkPath.addActionListener(BtnChooseJdkPathListener);

        tabbedPane.add("Key Generator", new PanelKeygen(this));
        tabbedPane.add("APK Signer", new PanelSigner(this));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtJdkPath = new javax.swing.JTextField();
        btnChooseJdkPath = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtJdkPath.setEditable(false);
        txtJdkPath.setBorder(javax.swing.BorderFactory.createTitledBorder("(For Windows users) JDK Path:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtJdkPath, gridBagConstraints);

        btnChooseJdkPath.setText("Choose...");
        jPanel1.add(btnChooseJdkPath, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(tabbedPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainFrame m = new MainFrame();
                UI.setWindowCenterScreen(m, 51);
                m.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseJdkPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtJdkPath;
    // End of variables declaration//GEN-END:variables
    private File jdkDir;

    /**
     * @return the keyFile
     */
    public File getJdkDir() {
        return jdkDir;
    }

    /**
     * @param v the keyFile to set
     */
    public void setJdkDir(File v) {
        this.jdkDir = v;
        txtJdkPath.setText(v.getAbsolutePath());

    }
    private final ActionListener BtnChooseJdkPathListener = new ActionListener() {

        public void actionPerformed(ActionEvent e) {
            File file = Files.chooseFile(null);
            if (file != null) {
                setJdkDir(file);
            }
        }
    };// BtnChooseJdkPathListener
}
