/*
 *    Copyright (C) 2012 Hai Bison
 *
 *    See the file LICENSE at the root directory of this project for copying
 *    permission.
 */

package group.pals.desktop.app.apksigner.ui.prefs;

import javax.swing.JPanel;

public class PanelInternetConnection extends JPanel {

    /**
     * Auto-generated by Eclipse.
     */
    private static final long serialVersionUID = 9066934128887563275L;

    /**
     * Create the panel.
     */
    public PanelInternetConnection() {

    }// PanelInternetConnection()

}
