/*
 *    Copyright (C) 2012 Hai Bison
 *
 *    See the file LICENSE at the root directory of this project for copying
 *    permission.
 */

/*
 * PanelSigner.java
 *
 * Created on Feb 15, 2012, 6:57:44 PM
 */
package group.pals.android.utils.apksigner.panels;

import group.pals.android.utils.apksigner.MainFrame;
import group.pals.android.utils.apksigner.panels.ui.JEditorPopupMenu;
import group.pals.android.utils.apksigner.utils.Files;
import group.pals.android.utils.apksigner.utils.MsgBox;
import group.pals.android.utils.apksigner.utils.ApkSigner;
import group.pals.android.utils.apksigner.utils.Constants;
import group.pals.android.utils.apksigner.utils.UI;
import group.pals.android.utils.apksigner.utils.prefs.Prefs;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import javax.swing.AbstractAction;

/**
 * The APK signer panel.
 *
 * @author Hai Bison
 */
public class PanelSigner extends javax.swing.JPanel {

    private final MainFrame mMainFrame;

    /**
     * Creates new form PanelSigner.
     *
     * @param mainFrame the main frame.
     */
    public PanelSigner(MainFrame mainFrame) {
        mMainFrame = mainFrame;

        initComponents();
        setKeyFile(null);
        setApkFile(null);

        mBtnLoadKeyFile.addActionListener(mBtnLoadKeyFileListener);
        mBtnLoadApkFile.addActionListener(mBtnLoadApkFileListener);
        mBtnSignFile.setAction(mActionSign);

        mTextPwd.addKeyListener(mTxtPwdKeyListener);
        UI.setEditorPopupMenu(this, new JEditorPopupMenu());
    }//PanelSigner()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mBtnLoadKeyFile = new javax.swing.JButton();
        mTextPwd = new javax.swing.JPasswordField();
        mTextAlias = new javax.swing.JTextField();
        mTextAliasPwd = new javax.swing.JPasswordField();
        mBtnLoadApkFile = new javax.swing.JButton();
        mBtnSignFile = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        mBtnLoadKeyFile.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mBtnLoadKeyFile, gridBagConstraints);

        mTextPwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mTextPwd.setBorder(javax.swing.BorderFactory.createTitledBorder("Password:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mTextPwd, gridBagConstraints);

        mTextAlias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mTextAlias.setBorder(javax.swing.BorderFactory.createTitledBorder("Alias:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mTextAlias, gridBagConstraints);

        mTextAliasPwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mTextAliasPwd.setBorder(javax.swing.BorderFactory.createTitledBorder("Alias password:"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mTextAliasPwd, gridBagConstraints);

        mBtnLoadApkFile.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mBtnLoadApkFile, gridBagConstraints);

        mBtnSignFile.setText("Sign!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(mBtnSignFile, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mBtnLoadApkFile;
    private javax.swing.JButton mBtnLoadKeyFile;
    private javax.swing.JButton mBtnSignFile;
    private javax.swing.JTextField mTextAlias;
    private javax.swing.JPasswordField mTextAliasPwd;
    private javax.swing.JPasswordField mTextPwd;
    // End of variables declaration//GEN-END:variables
    /**
     * Preferences
     */
    private final Prefs mPrefs = Prefs.getInstance();
    private static final String KEY_KEYFILE_LAST_WORKING_DIR = PanelSigner.class.getName() + ".key-file-last-working-dir";
    private static final String KEY_APK_FILE_LAST_WORKING_DIR = PanelSigner.class.getName() + ".apk-file-last-working-dir";
    private File mKeyFile;

    /**
     * Gets the keystore file.
     *
     * @return the key file
     */
    public File getKeyFile() {
        return mKeyFile;
    }//getKeyFile()

    /**
     * Sets the keystore file.
     *
     * @param file the key file to set.
     */
    public void setKeyFile(File file) {
        mKeyFile = file;
        mBtnLoadKeyFile.setText(file == null ? "Load key-file..." : String.format("[ %s ]", file.getName()));
        mBtnLoadKeyFile.setForeground(file == null ? Color.cyan : UI.COLOUR_SELECTED_FILE);
    }//setKeyFile()
    private File mApkFile;

    /**
     * Gets the APK file.
     *
     * @return the APK file.
     */
    public File getApkFile() {
        return mApkFile;
    }//getApkFile()

    /**
     * Sets the APK file.
     *
     * @param file the APK file to set.
     */
    public void setApkFile(File file) {
        mApkFile = file;
        mBtnLoadApkFile.setText(file == null ? "Load apk-file..." : String.format("[ %s ]", file.getName()));
        mBtnLoadApkFile.setForeground(file == null ? Color.cyan : UI.COLOUR_SELECTED_FILE);
    }//setApkFile()

    /*
     * LISTENERS
     */
    private final ActionListener mBtnLoadKeyFileListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            File f = Files.chooseFile(new File(mPrefs.get(KEY_KEYFILE_LAST_WORKING_DIR, "/")),
                    Constants.REGEX_KEYSTORE_FILES, Constants.DESC_KEYSTORE_FILES);
            if (f != null) {
                setKeyFile(f);
                mPrefs.set(KEY_KEYFILE_LAST_WORKING_DIR, f.getParent());
            }
        }//actionPerformed()
    };//mBtnLoadKeyFileListener
    private final ActionListener mBtnLoadApkFileListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            File f = Files.chooseFile(new File(mPrefs.get(KEY_APK_FILE_LAST_WORKING_DIR, "/")),
                    Constants.REGEX_APK_FILES, Constants.DESC_APK_FILES);
            if (f != null) {
                setApkFile(f);
                mPrefs.set(KEY_APK_FILE_LAST_WORKING_DIR, f.getParent());
            }
        }//actionPerformed()
    };//mBtnLoadApkFileListener
    private final AbstractAction mActionSign = new AbstractAction("Sign!") {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (getKeyFile() == null || !getKeyFile().isFile()) {
                MsgBox.showErrMsg(null, null, "Key-file does not exist");
                return;
            }
            if (getApkFile() == null || !getApkFile().isFile()) {
                MsgBox.showErrMsg(null, null, "APK file does not exist");
                return;
            }
            String alias = String.valueOf(mTextAlias.getText());
            if (alias.isEmpty()) {
                MsgBox.showErrMsg(null, null, "Alias is empty");
                return;
            }

            try {
                String info = ApkSigner.sign(mMainFrame.getJdkDir(),
                        getApkFile(), getKeyFile(), mTextPwd.getPassword(), alias,
                        mTextAliasPwd.getPassword());
                if (info == null || info.isEmpty()) {
                    MsgBox.showInfoMsg(null, null, "APK is signed");
                } else {
                    MsgBox.showHugeInfoMsg(null, null, info, 800, 450);
                }
            } catch (Exception ex) {
                MsgBox.showErrMsg(null, null, "Error while signing file. Please try again.\n\nDetails:\n\n" + ex);
            }
        }//actionPerformed()
    };//mActionSign
    /**
     * TODO: load aliases automatically, and let user to be able to choose them
     */
    private final KeyListener mTxtPwdKeyListener = new KeyAdapter() {
        @Override
        public void keyTyped(KeyEvent e) {
//            try {
//                KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
//
//                char[] pwd = txtPwd.getPassword();
//                
//                java.io.FileInputStream fis = null;
//                try {
//                    fis = new java.io.FileInputStream("keyStoreName");
//                    ks.load(fis, pwd);
//
//                    // get my private key
//                    KeyStore.PrivateKeyEntry pkEntry = (KeyStore.PrivateKeyEntry) ks.getEntry("privateKeyAlias", pwd);
//                    PrivateKey myPrivateKey = pkEntry.getPrivateKey();
//                } finally {
//                    if (fis != null) {
//                        fis.close();
//                    }
//                }
//            } catch (Exception ex) {
//            }
        }
    };//mTxtPwdKeyListener
}
